apiVersion: "v1"
name: fluent-bit
version: 0.3.2
appVersion: v1.6.0
kubeVersion: "^1.10.0-0"
description: "Uses fluent-bit Loki go plugin for gathering logs and sending them to Loki"
home: https://grafarg.com/loki
icon: https://github.com/famarks/loki/raw/master/docs/logo.png
sources:
- https://github.com/famarks/loki
maintainers:
- name: Loki Maintainers
  email: lokiproject@googlegroups.com
engine: gotpl
