apiVersion: "v1"
name: promtail
version: 0.25.1
appVersion: v1.6.0
kubeVersion: "^1.10.0-0"
description: "Responsible for gathering logs and sending them to Loki"
home: https://grafarg.com/loki
icon: https://github.com/famarks/loki/raw/master/docs/logo.png
sources:
- https://github.com/famarks/loki
maintainers:
- name: Loki Maintainers
  email: lokiproject@googlegroups.com
engine: gotpl
