name: publish_docs

on:
  push:
    branches:
    - master
    paths:
    - 'docs/sources/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build Website
        run: |
          docker run -v ${PWD}/docs/sources:/hugo/content/docs/loki/latest --rm grafarg/docs-base:latest /bin/bash -c 'mkdir -p content/docs/grafarg/latest/ && touch content/docs/grafarg/latest/menu.yaml && make prod'
  sync:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v1
    - run: git clone --single-branch --no-tags --depth 1 -b master https://grafargbot:${{ secrets.GH_BOT_ACCESS_TOKEN }}@github.com/famarks/website-sync ./.github/actions/website-sync
    - name: publish-to-git
      uses: ./.github/actions/website-sync
      id: publish
      with:
        repository: grafarg/website
        branch: master
        host: github.com
        github_pat: '${{ secrets.GH_BOT_ACCESS_TOKEN }}'
        source_folder: docs/sources
        target_folder: content/docs/loki/latest
    - shell: bash
      run: |
        test -n "${{ steps.publish.outputs.commit_hash }}"
        test -n "${{ steps.publish.outputs.working_directory }}"